title: <p align="Centre"> Veda Vyas </p> 
logo: /assets/img/logo.png
description: I am Qualified Chartered Accountant working as Project lead in S&P Global.Presently working on Data tranformation projects with machine learning models.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
